#!/bin/sh -eu
rule=" FORWARD -m physdev --physdev-is-bridged -j ACCEPT"
iptables -C $rule 2>/dev/null || iptables -I $rule

test -z "${IF_GATEWAY:-}" && exit 0

rule=" POSTROUTING -o $IFACE -t nat -j MASQUERADE"
if [ $MODE = "start" ]
then
  iptables -C $rule 2>/dev/null || iptables -I $rule
elif [ $MODE = "stop" ]
then
  iptables -C $rule 2>/dev/null && iptables -D $rule
fi
