#!/bin/bash -eu

# re-exec as root
set -eu
if [ "$(id -u)" != 0 ]
then
  exec sudo -n "$(readlink -f "$0")"
fi

# reset the iptables state.
for table in filter nat mangle raw security
do
  iptables -F -t "$table"
  iptables -X -t "$table"

  ip6tables -F -t "$table"
  ip6tables -X -t "$table"
done

iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -P INPUT DROP

iptables -t filter -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -P FORWARD DROP

# bridges
for br in docker0 natbr0 zerobr0
do
  iptables -t filter -I INPUT -i "${br}" -j ACCEPT
  iptables -t filter -I FORWARD -i "${br}" -j ACCEPT
done

# ipv6 tables
ip6tables -t filter -P INPUT DROP
ip6tables -t filter -P FORWARD DROP
ip6tables -t filter -A INPUT -i lo -j ACCEPT
ip6tables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
ip6tables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
ip6tables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
ip6tables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT

if [ -r /etc/fw.local ]
then
  source /etc/fw.local
fi
