#!/bin/bash -eux

unset GOROOT GOPATH
export PATH="/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
export PATH="/usr/lib/go-1.24/bin:$PATH"

version="${1:-origin/master}"
builduser="${K8S_BUILDUSER:-$USER}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

srcdir="/opt/kubernetes/src/kubernetes"
cd "${srcdir}"

git fetch -a
git clean -dfx
git checkout "${version}"

destdir="/opt/kubernetes/bin"
mkdir -p "${destdir}"

cd "${srcdir}"
declare -a go cmds

export KUBE_ROOT="${srcdir}"
export KUBE_GO_PACKAGE=""
export CGO_ENABLED=0

# shellcheck disable=SC1090
source "${srcdir}/hack/lib/version.sh"

go=(go build -gcflags=-trimpath=${srcdir} -v -mod=vendor "-tags=providerless,dockerless" -ldflags "$(kube::version::ldflags|sed 's^/vendor/^^g')" )

cmds=(
  kube-apiserver
  kube-controller-manager
  kube-scheduler
  kube-proxy
  kubelet
  kubectl
  kubeadm
  cloud-controller-manager
)

for d in "${cmds[@]}"
do
  "${go[@]}" -o "${destdir}/${d}" "./cmd/${d}"
  strip "${destdir}/${d}"
done
