#!/bin/bash
set -eu

export PATH="/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
export PATH="/usr/lib/go-1.15/bin:$PATH"

builduser="${GOTOOLS_BUILDUSER:-gotoolsbuild}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

export GOPATH="$HOME"
export GO_BIN="$GOPATH/bin"
export GO111MODULE=on

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

mkdir -p "$GOPATH"

cd "$GOPATH"

# shellcheck disable=SC2016
echo -e 'export GOPATH=$(pwd)\nexport GO111MODULE=on\n' > "$GOPATH/.envrc"
echo -e '*\n!.envrc\n!.versions' > "$GOPATH/.gitignore"

# record versions
recordVersions() {
  find ./bin -type f -perm 0755 -print0|xargs -0 -n1 go version -m > .versions

  git init -q .

  if [ "$(git diff)$(git diff --cached)" != "" ]
  then
    git add .
    git commit -am "gotools update: $(date -Iseconds)"
  fi
}

# golang dev tools
cat <<- END |xargs -n1 -IX go get -v X@latest
github.com/golangci/golangci-lint/cmd/golangci-lint
github.com/rogpeppe/godef
github.com/lukehoban/go-outline
sourcegraph.com/sqs/goreturns
github.com/tpng/gopkgs
github.com/newhook/go-symbols
github.com/jstemmer/gotags
github.com/fatih/motion
github.com/zmb3/gogetdoc
github.com/josharian/impl
golang.org/x/lint/golint
golang.org/x/tools/gopls
github.com/fatih/gomodifytags
github.com/klauspost/asmfmt/cmd/asmfmt
github.com/davidrjenni/reftools/cmd/fillstruct
END

# applications written in golang
cat <<- END |xargs -n1 -IX go get -v X@latest
code.gitea.io/tea
github.com/ddollar/forego
github.com/github/hub
github.com/ericchiang/pup
github.com/junegunn/fzf
github.com/hoskeri/liverebuild
github.com/vmware/govmomi/govc
github.com/cosmos72/gomacro
cuelang.org/go/cmd/cue
github.com/fullstorydev/grpcurl/cmd/grpcurl
END

recordVersions

strip ./bin/*

printf "***\n*** update-gotools complete\n***\n"
