#!/bin/bash -eux

name=kustomize
version="4.2.0"
filename="${name}_v${version}_linux_amd64"

builduser="${KUSTOMIZE_BUILDUSER:-$USER}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

url="https://github.com/kubernetes-sigs/${name}/releases/download/kustomize%2Fv${version}/${filename}.tar.gz"

bindir="${HOME}/bin"
webdir="${HOME}/.cache/update-${name}"
etag="${webdir}/${filename}.etag"

mkdir -p "${bindir}" "${webdir}"

curl -sSfLo "${webdir}/${filename}.tar.gz" --etag-save "${etag}" --etag-compare "${etag}" "$url"
tar -C "${bindir}" --strip-components=0 -axf "${webdir}/${filename}.tar.gz" "${name}"
