#!/bin/bash
set -eux

unset GOPATH GOROOT
export PATH="/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"

# Go version: $GO_VERSION > ./.go-version (walk-up) > ~/.config/go-version
govers="$("${HOME}/bin/go-version")"
if [ -z "${govers}" ] || [ ! -x "/usr/lib/go-${govers}/bin/go" ]
then
  echo "update-gotools: no Go toolchain for version '${govers:-}' (set GO_VERSION, add a .go-version, or write ~/.config/go-version)" >&2
  exit 1
fi
export PATH="/usr/lib/go-${govers}/bin:$PATH"
unset govers

builduser="${GOTOOLS_BUILDUSER:-$USER}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

export CGO_ENABLED=0
export GOPATH="$HOME/.gotools-install"
export GO_BIN="$GOPATH/bin"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

mkdir -p "$GOPATH"

cd "$GOPATH"

# shellcheck disable=SC2016
echo -e 'export GOPATH=$(pwd)\nexport GO111MODULE=on\n' > "$GOPATH/.envrc"
echo -e '*\n!.envrc\n!.versions' > "$GOPATH/.gitignore"

# record versions
recordVersions() {
  find ./bin -type f -perm 0755 -print0|xargs -0 -n1 go version -m > .versions

  git init -q .

  if [ "$(git diff)$(git diff --cached)" != "" ]
  then
    git add .
    git commit -am "gotools update: $(date -Iseconds)"
  fi
}

# golang dev tools
cat <<- END |xargs -t -IX go install X@latest
github.com/golangci/golangci-lint/cmd/golangci-lint
golang.org/x/lint/golint
golang.org/x/tools/gopls
google.golang.org/grpc/cmd/protoc-gen-go-grpc
google.golang.org/protobuf/cmd/protoc-gen-go
github.com/jondot/goweight
END

# applications written in golang
cat <<- END |xargs -t -IX go install X@latest
github.com/ddollar/forego
github.com/ericchiang/pup
github.com/junegunn/fzf
github.com/hoskeri/liverebuild
github.com/cosmos72/gomacro
cuelang.org/go/cmd/cue
github.com/containernetworking/cni/cnitool
github.com/fullstorydev/grpcurl/cmd/grpcurl
sigs.k8s.io/kind
github.com/itchyny/gojq/cmd/gojq
github.com/google/ko
github.com/moorereason/mdfmt
END

recordVersions

strip ./bin/*

printf "***\n*** update-gotools complete\n***\n"
