#!/bin/bash -eux

version="3.4.15"
filename="etcd-v${version}-linux-amd64"

builduser="${ETCD_BUILDUSER:-etcd-build}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

url="https://github.com/etcd-io/etcd/releases/download/v${version}/${filename}.tar"

bindir="${HOME}/bin"
webdir="${HOME}/.cache/update-etcd"
etag="${webdir}/${filename}.etag"

mkdir -p "${bindir}" "${webdir}"

curl -sSfLo "${webdir}/${filename}.tar" --etag-save "${etag}" --etag-compare "${etag}" "$url"
tar -C "${bindir}" --strip-components=1 -xf "${webdir}/${filename}.tar" "${filename}/etcd" "${filename}/etcdctl"
