#!/bin/bash -eux
version="1.4.6"
tmpfile="$(mktemp /tmp/update-terraform.XXXXXX)"
terraform_bin="${HOME}/bin/terraform"

builduser="${TRFM_BUILDUSER:-$USER}"
self="$(readlink -f "$0")"

if [ "$(id -u "$builduser")" != "$UID" ]
then
  exec sudo -H -u "$builduser" "$self"
fi

trap 'rm -f "$tmpfile"' EXIT

mkdir -p "${HOME}/bin"

curl -o "${tmpfile}" -sSfL "https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_amd64.zip"
unzip -p -l  "${tmpfile}" terraform > "${terraform_bin}"
chmod 0755 "${terraform_bin}"
